# Fase de construcción
FROM node:18-alpine AS build

# Establece el directorio de trabajo
WORKDIR /usr/src/app/expenseMateApp

# Copia los archivos de configuración de la aplicación
COPY expenseMateApp/package*.json ./
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY expenseMateApp/. .

# Construye la aplicación Angular
RUN npm run build --prod

# Fase de producción
FROM nginx:alpine

# Copia la carpeta dist de Angular al contenedor NGINX
COPY --from=build /usr/src/app/expenseMateApp/dist/expense-mate-app /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]
