version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expensemate
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql  # Asegúrate de que init.sql esté en /backend
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db

  backend:
    build: ./backend  # Se asume que tienes un Dockerfile en /backend
    ports:
      - "4000:3000"
    env_file:
      - ./backend/.env  # Variables de entorno para el backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    networks:
      - expensemate-network

  frontend:
    build: ./frontend  # Se asume que tienes un Dockerfile en /frontend
    ports:
      - "4200:80"  # Angular utiliza el puerto 80 en el contenedor
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - expensemate-network

volumes:
  postgres_data:

networks:
  expensemate-network:
    driver: bridge
