FROM node:18

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de configuración de npm
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el contenido de la carpeta src
COPY ./src ./src

# Expone el puerto en el que la app estará escuchando
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "src/index.js"]
